languageCode = "en-us"
title = "David Nguyen's Personal Blog"
theme = "dream-plus"


paginate = 10
enableRobotsTXT = true
disqusShortname = "pnguyen"

#Skip building these files
ignoreFiles = ["content/cards/\\.*", "content/404.md"]

#Syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	#Favicon for site
	favicon = "images/favicon.ico"

	#Set whether you're hosting "cards" or "post"
	contentType = "posts"

	siteStartYear = 2018

	[params.author]
		name = "David Nguyen"
		description = "Just a regular developer who's passionate about crafting high quality software, a martial arts practitioner, a proud dad of two sons."
		avatar = "https://www.gravatar.com/avatar/624eb530503fe6117f4b4b5ad3acf062?s=150"
		motto = "Developer & Karateka"

	[params.features]
		#Enable Twitter Emoji
		twitterEmoji = true
		#Enable Table of Contents
		toc = true
		#Enable share card
		shareCard = true
		#Use custom CSS
		customCSS = ["/css/highlight.css"]

	[params.background]
		bgColor = "linear-gradient(to bottom, #13547A, #70BEBC)"

	#Tags settings
	[params.tags]
		enabled = true

	#Categories settings
	[params.categories]
		enabled = true

[social]
	github = "hpcsc"
	linkedin = "nguyenhungphuong"
	codeproject = "hpcsc"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
