backend:
  name: github
  repo: hpcsc/personal-blog
  branch: master

publish_mode: editorial_workflow
media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    path: '{{slug}}/index'
    media_folder: images
    public_folder: images
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Cover", name: "cover", widget: "string", default: "/images/card-default-cover.png"}
      - {label: "Body", name: "body", widget: "markdown"}
