name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        run: make install_hugo

      - name: Build
        run: make build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          publish_branch: master
          allow_empty_commit: true
          external_repository: hpcsc/hpcsc.github.io
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'hpcsc@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          cname: pnguyen.io
